[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/tendermint/go-amino"
  version = "v0.14.0"

[[constraint]]
  name = "github.com/ColorPlatform/prism"
  version = "v0.0.0-20190603094734-d7a6196c61b7"

[prune]
  go-tests = true
  unused-packages = true
